openapi: 3.0.3
info:
  title: Simple yaml
  version : "0.1.0"
  description: A simple yaml to test against.
paths:
  /test:
    put:
      operationId: test
      responses:
        '200':
          description: 'please stop giving me red'
components:
  schemas:
    EmptyBean:
      type: object
      description: An empty bean with no properties

    BeanWithPrimitiveProperty:
      type: object
      description: A bean with a single primitive property
      properties:
        aStringVariable:
          type: string
    
    BeanWithMultiplePrimitiveProperties:
      type: object
      description: A bean with multiple primitive properties
      properties:
        aStringVariable:
          type: string
        aIntVariable:
          type: integer
    
    BeanForTestingAllPrimitivePropertyTypes:
      type: object
      description: A bean that tests all primitive property types (except arrays)
      properties:
        aStringVariable:
          type: string
          description: this should be a String in a java bean
        aIntVariable:
          type: integer
          description: this should be an int in a java bean
        aNumberVariable:
          type: number
          description: this should be a float in the java bean
        aBooleanVariable:
          type: boolean
    
    BeanWithArray:
      type: object
      description: A bean that tests arrays
      properties:
        anArrayVariable:
          type: array
          items:
            type: string
    
    BeanToTestArraysWithVariousPrimitiveTypes:
      type: object
      description: A bean to test array property can contain any primitive property type
      properties:
        aStringArray:
          type: array
          items:
            type: string
        anIntArray:
          type: array
          items: 
            type: integer
        aNumberArray:
          type: array
          items:
            type: number
        aBooleanArray:
          type: array
          items:
            type: boolean
    
    BeanWithMixOfArrayAndPrimitiveProperties:
      type: object
      description: A bean with a mix of arrays and other primitive property types
      properties:
        anArrayVariable:
          type: array
          items:
            type: string
        aStringVariable:
          type: string
        anIntArray:
          type: array
          items:
            type: integer
        anIntVariable:
          type: integer
    
    BeanWithPropertyReferencingEmptyBean:
      type: object
      description: A bean to test referencing functionality
      properties:
        referencingProperty:
          $ref: '#/components/schemas/EmptyBean'
    
    BeanWithEnumProperty:
      type: object
      description: bean with a reference to an enum
      properties:
        anEnumProperty:
          type: string
          description: an enum with 2 values to test against.
          enum: [string1, string2]
    
    BeanWithArrayOfReferenceToEmptyBean:
      type: object
      description: A bean that tests arrays
      properties:
        anArrayVariable:
          type: array
          items:
            $ref: '#/components/schemas/EmptyBean'

    BeanWithRequiredPrimitiveProperty:
      type: object
      description: A bean with a single primitive property
      required: [aStringVariable]
      properties:
        aStringVariable:
          type: string