@startuml "java-class"

class JavaPackage {
    {field} name : string
}

class JavaClass {
    {field} name : string
    {field} description : string
    {field} includes : []string
}

JavaClass "*" --> "1" JavaPackage : javaPackage
JavaPackage "1" *--> "*" JavaClass : classes

class DataMember {
    {field} name : string
    {field} type : string
    {field} description : string
}

JavaClass *--> DataMember : dataMembers

class JavaEnum {
    {field} name : string
    {field} description : string
    {field} enumValues : []string
}

JavaPackage "1" *--> JavaEnum : enums
JavaEnum "*" --> "1" JavaPackage : javaPackage

class JavaInterface {
    {field} name : string
    {field} description : string
}

JavaInterface "*" --> "1" JavaPackage : javaPackage
JavaPackage "1" *--> "*" JavaInterface : interfaces
JavaClass "*" --> "1" JavaInterface : inheritedInterface
JavaInterface "1" *--> "*" JavaClass : classes

@enduml